// src/routes/contact/+page.svelte
<script lang="ts">
	import { enhance } from '$app/forms';

	interface MessageType {
		type: 'info' | 'success' | 'error';
		text: string;
	}

	let message: MessageType | undefined = undefined;

	const inputs = [
		{
			type: 'text',
			name: 'contact',
			label: 'Your Name',
			required: true,
			placeholder: 'e.g Rodgers M Gitau'
		},
		{
			type: 'text',
			name: 'company',
			label: 'Company',
			required: false,
			placeholder: 'e.g Top Brand Limited'
		},
		{
			type: 'tel',
			name: 'phoneNumber',
			label: 'Phone Number',
			required: false,
			placeholder: 'e.g +254712345678'
		},
		{
			type: 'email',
			name: 'email',
			label: 'Email',
			required: true,
			placeholder: 'e.g rodgersgitau@example.com'
		}
	];
	const alertStyling = (type: MessageType['type']) => {
		switch (type) {
			case 'error':
				return 'bg-pink-100 text-pink-900';
			case 'success':
				return 'bg-emerald-100 text-emerald-900';
			default:
				return 'bg-pink-100 text-black';
		}
	};
</script>

<svelte:head>
	<title>Contact</title>
</svelte:head>

<div class="overflow-y-auto h-full w-90 md:w-[45vw] mx-auto">
	<h1 class="text-xl font-black text-black dark:text-gray-400">
		Leave some details and I will reach out ...
	</h1>
	{#if message}
		<div
			class={`${alertStyling(message.type)} w-full px-4 py-2.5 flex items-center gap-8 rounded-md`}
		>
			<p class="flex-1 text-sm font-semibold">{message.text}</p>
			<button
				on:click={() => {
					message = undefined;
				}}
				class="text-lg font-semibold bg-transparent"
			>
				x
			</button>
		</div>
	{/if}
	<form
		use:enhance
		method="POST"
		action="?/submitMessage"
		name="RGitauContactForm"
		class="flex flex-col flex-1 w-full h-full gap-5 py-4 md:grid md:gap-10 md:grid-cols-2"
	>
		<p class="hidden">
			<label id="contact-form-bot-label">
				Don't fill this out if you're human:{' '}
				<input name="bot-field" aria-labelledby="contact-form-bot-label" />
			</label>
		</p>

		{#each inputs as { name, label, required, ...rest }}
			<div
				class="relative z-0 flex flex-col-reverse w-full gap-2 text-sm text-black group dark:text-gray-400"
			>
				<input
					{...rest}
					id={name}
					{name}
					{required}
					class="py-2.5 px-0 w-full bg-transparent placeholder:text-gray-600 dark:placeholder:text-gray-500 appearance-none border-0 border-b-2 border-gray-600 dark:border-gray-300 focus:border-pink-600 dark:focus:border-pink-600 focus:outline-none focus:ring-0 peer"
				/>
				<label for={name} class="text-sm font-semibold peer-focus:text-pink-500">
					<div class="flex items-center gap-1">
						<span>{label}</span>
						{#if required}
							<sup>*</sup>
						{/if}
					</div>
				</label>
			</div>
		{/each}

		<div
			class="relative z-0 flex flex-col-reverse w-full col-span-2 gap-3 text-sm text-black group dark:text-gray-400"
		>
			<textarea
				rows={8}
				id="message"
				name="message"
				maxLength={300}
				placeholder="e.g I liked your portfolio and would like to discuss working on a project"
				class="p-2.5 w-full rounded-md bg-transparent placeholder:text-gray-600 dark:placeholder:text-gray-500 appearance-none border-2 border-gray-600 dark:border-gray-300 focus:border-pink-600 focus:outline-none focus:ring-0 peer"
			/>
			<label for="message" class="text-sm font-semibold peer-focus:text-pink-500">
				Your Message
			</label>
		</div>
		<button
			type="submit"
			class="col-span-2 text-white bg-black/75 dark:bg-pink-600/75 hover:bg-black dark:hover:bg-pink-600 focus:ring-4 focus:outline-none focus:ring-pink-300 font-medium rounded-lg text-md w-full sm:w-auto px-5 py-2.5 text-center dark:opacity-100"
		>
			Request For Callback
		</button>
	</form>
	<small class="text-xs text-right text-black dark:text-gray-500"> * Required Fields </small>
</div>

// app/contact/page.tsx
const ContactPage = () => {
  return (
    <section className="flex items-center justify-center">
      <div className="w-90 md:w-[40vw] h-full py-8">
        <form className="flex flex-col gap-8">
          <div className="grid md:grid-cols-2 md:gap-6">
            <div className="relative z-0 w-full mb-6 group">
              <input
                type="text"
                name="floating_first_name"
                id="floating_first_name"
                className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-purple-500 focus:outline-none focus:ring-0 focus:border-purple-600 peer"
                placeholder=" "
                required
              />
              <label
                htmlFor="floating_first_name"
                className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -tranpurple-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:tranpurple-y-0 peer-focus:scale-75 peer-focus:-tranpurple-y-6"
              >
                First name
              </label>
            </div>
            <div className="relative z-0 w-full mb-6 group">
              <input
                type="text"
                name="floating_last_name"
                id="floating_last_name"
                className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-purple-500 focus:outline-none focus:ring-0 focus:border-purple-600 peer"
                placeholder=" "
                required
              />
              <label
                htmlFor="floating_last_name"
                className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -tranpurple-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:tranpurple-y-0 peer-focus:scale-75 peer-focus:-tranpurple-y-6"
              >
                Last name
              </label>
            </div>
          </div>
          <div className="relative z-0 w-full mb-6 group">
            <input
              type="email"
              name="floating_email"
              id="floating_email"
              className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-purple-500 focus:outline-none focus:ring-0 focus:border-purple-600 peer"
              placeholder=" "
              required
            />
            <label
              htmlFor="floating_email"
              className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -tranpurple-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:tranpurple-y-0 peer-focus:scale-75 peer-focus:-tranpurple-y-6"
            >
              Email address
            </label>
          </div>
          <div className="grid md:grid-cols-2 md:gap-6">
            <div className="relative z-0 w-full mb-6 group">
              <input
                type="tel"
                pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}"
                name="floating_phone"
                id="floating_phone"
                className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-purple-500 focus:outline-none focus:ring-0 focus:border-purple-600 peer"
                placeholder=" "
                required
              />
              <label
                htmlFor="floating_phone"
                className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -tranpurple-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:tranpurple-y-0 peer-focus:scale-75 peer-focus:-tranpurple-y-6"
              >
                Phone number (123-456-7890)
              </label>
            </div>
            <div className="relative z-0 w-full mb-6 group">
              <input
                type="text"
                name="floating_company"
                id="floating_company"
                className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-purple-500 focus:outline-none focus:ring-0 focus:border-purple-600 peer"
                placeholder=" "
                required
              />
              <label
                htmlFor="floating_company"
                className="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -tranpurple-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-purple-600 peer-focus:dark:text-purple-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:tranpurple-y-0 peer-focus:scale-75 peer-focus:-tranpurple-y-6"
              >
                Company (Ex. Google)
              </label>
            </div>
          </div>
          <button
            type="submit"
            className="text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-300 font-medium rounded-lg text-md w-full sm:w-auto px-5 py-2.5 text-center dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-800"
          >
            Request For Callback
          </button>
        </form>
      </div>
    </section>
  );
};
export default ContactPage;
